export const eventTypes = new Map([
    [1, 'Froid inhabituel'],
    [2, 'Episode neigeux'],
    [3, 'Douceur inhabituelle'],
    [4, 'Episode pluvieux'],
    [5, 'Inondation'],
    [6, 'Tempête/coup de vent'],
    [7, 'Cyclone'],
    [8, 'Chaleur'],
    [9, 'Orages'],
    [10, 'Sécheresse'],
    [11, 'Pluies verglacantes'],
    [12, 'Gelées tardives'],
    [13, 'Gelées précoces'],
    [14, 'Froid'],
    [15, 'Grêle'],
    [16, 'Episode neigeux tardif'],
    [17, 'Episode neigeux précoce'],
    [18, 'Tornade'],
    [19, 'Dépression extra-tropicale'],
    [20, 'Tempête tropicale'],
    [-1, 'autres'],
]);

export const localisations    = new Map([
    [42, 'Alsace'],
    [72, 'Aquitaine'],
    [83, 'Auvergne'],
    [26, 'Bourgogne'],
    [53, 'Bretagne'],
    [21, 'Champagne-Ardenne'],
    [94, 'Corse'],
    [43, 'Franche-Comté'],
    [11, 'Ile-de-France'],
    [91, 'Languedoc-Roussillon'],
    [74, 'Limousin'],
    [24, 'Centre'],
    [41, 'Lorraine'],
    [73, 'Midi-Pyrénées'],
    [31, 'Nord-pas-de-calais'],
    [25, 'Basse-Normandie'],
    [23, 'Haute-Normandie'],
    [52, 'Pays de la Loire'],
    [22, 'Picardie'],
    [54, 'Poitou-Charentes'],
    [93, 'PACA'],
    [82, 'Rhônes-Alpes'],

]);